--# selene: allow(unused_variable)
--# selene: allow(unscoped_variables)
---@meta

do
	---@class SrcCamera
	---@field pos Vector
	---@field rot RotMatrix
	---@field fov number
	local SrcCamera
end

do
	---@class SrcPointWidget
	---@field enabled boolean
	---@field x number
	---@field y number
	---@field anchor integer
	---@field defaultX number
	---@field defaultY number
	---@field defaultAnchor integer
	local SrcPointWidget
end

do
	---@class SrcTextWidget
	---@field enabled boolean
	---@field x number
	---@field y number
	---@field anchor integer
	---@field size number
	---@field align integer
	---@field r number
	---@field g number
	---@field b number
	---@field a number
	---@field defaultX number
	---@field defaultY number
	---@field defaultAnchor integer
	---@field defaultSize number
	---@field defaultAlign integer
	local SrcTextWidget
end

do
	---@class SrcScaleWidget
	---@field enabled boolean
	---@field x number
	---@field y number
	---@field anchor integer
	---@field scale number
	---@field defaultX number
	---@field defaultY number
	---@field defaultAnchor integer
	---@field defaultScale number
	local SrcScaleWidget
end

do
	---@class SrcMinimapWidget
	---@field enabled boolean
	---@field x number
	---@field y number
	---@field anchor integer
	---@field size number
	---@field defaultX number
	---@field defaultY number
	---@field defaultAnchor integer
	---@field defaultSize number
	local SrcMinimapWidget
end

do
	---@class SrcProgressBarWidget
	---@field enabled boolean
	---@field x number
	---@field y number
	---@field anchor integer
	---@field width number
	---@field height number
	---@field defaultX number
	---@field defaultY number
	---@field defaultAnchor integer
	---@field defaultWidth number
	---@field defaultHeight number
	local SrcProgressBarWidget
end

do
	---@class SrcStaminaBarWidget
	---@field enabled boolean
	---@field x number
	---@field y number
	---@field anchor integer
	---@field width number
	---@field height number
	---@field capOffsetY number
	---@field defaultX number
	---@field defaultY number
	---@field defaultAnchor integer
	---@field defaultWidth number
	---@field defaultHeight number
	---@field defaultCapOffsetY number
	local SrcStaminaBarWidget
end

do
	---@class SrcCrosshairWidget
	---@field enabled boolean
	---@field x number
	---@field y number
	---@field anchor integer
	---@field scale number
	---@field style integer
	---@field visibleWhileAiming boolean
	---@field defaultX number
	---@field defaultY number
	---@field defaultAnchor integer
	---@field defaultScale number
	---@field defaultStyle integer
	---@field defaultVisibleWhileAiming boolean
	local SrcCrosshairWidget
end

do
	---@class SrcInventoryWidgets
	---@field panel SrcPointWidget
	---@field equipmentPanel SrcPointWidget
	---@field directionWidget SrcPointWidget
	local SrcInventoryWidgets
end

do
	---@class SrcHudWidgets
	---@field inventory SrcInventoryWidgets
	---@field minimap SrcMinimapWidget
	---@field crosshair SrcCrosshairWidget
	---@field staminaBar SrcStaminaBarWidget
	---@field moveModeText SrcTextWidget
	---@field chatModeText SrcTextWidget
	---@field progressBar SrcProgressBarWidget
	---@field phonePrompts SrcTextWidget
	---@field midgetWidget SrcPointWidget
	---@field messageRing SrcPointWidget
	---@field pressTabHint SrcTextWidget
	---@field moneyText SrcTextWidget
	---@field teamMoneyText SrcTextWidget
	---@field roundStartText SrcTextWidget
	---@field roundResultText SrcTextWidget
	---@field roleRevealText SrcTextWidget
	---@field saviorText SrcTextWidget
	---@field chatFeed SrcPointWidget
	---@field mapToggleHint SrcTextWidget
	local SrcHudWidgets
end

do
	---@class SrcLocalClient
	---@field player Player?
	---@field human Human?
	---@field spectatingHuman Human?
	---@field camera SrcCamera
	---@field isMapToggled integer
	---@field isInGame integer
	---@field menuState integer
	---@field enableMouse integer
	---@field isTabMenu integer
	---@field isPauseMenu integer
	---@field ping integer
	---@field isMapAutoGenerated integer
	---@field mapLegendPosX number
	---@field mapLegendPosY number
	---@field serverAddress string
	---@field serverPort integer
	---@field ticksSinceReset integer
	---@field hud SrcHudWidgets
	local SrcLocalClient
end

do
	---@class SrcSounds
	---@field loadSound fun(self: SrcSounds, path: string, maxDistance?: number): integer
	---@field playSound3D fun(self: SrcSounds, soundId: integer, position: Vector, volume?: number, pitch?: number): integer
	---@field stopSound fun(self: SrcSounds, emitterId: integer)
	local SrcSounds
end

do
	---@class SrcPngImage
	---@field atlas integer
	---@field id integer
	---@field width integer
	---@field height integer
	---@field path string
	---@field isValid boolean
	local SrcPngImage
end

do
	---@class SrcRenderer
	---@field enableHead boolean
	---@field drawText fun(self: SrcRenderer, text: string, x: number, y: number, size: number, r: number, g: number, b: number, a: number, align: integer)
	---@field worldToScreenPosition fun(self: SrcRenderer, world: Vector): number?, number?
	---@field drawSquare2D fun(self: SrcRenderer, x: number, y: number, size: number, r: number, g: number, b: number, a: number)
	---@field drawRectangle2D fun(self: SrcRenderer, x: number, y: number, w: number, h: number, r: number, g: number, b: number, a: number)
	---@field drawRectangleRotated2D fun(self: SrcRenderer, x: number, y: number, w: number, h: number, rot: number, r: number, g: number, b: number, a: number)
	---@field drawMapCircle fun(self: SrcRenderer, x: number, y: number, radius: number, r: number, g: number, b: number, a: number)
	---@field drawDebugLine3D fun(self: SrcRenderer, from: Vector, to: Vector, r: number, g: number, b: number, a: number)
	---@field drawDebugWireBox3D fun(self: SrcRenderer, pos: Vector, rot: RotMatrix, sx: number, sy: number, sz: number, r: number, g: number, b: number, a: number)
	---@field drawDebugSolidBox3D fun(self: SrcRenderer, pos: Vector, rot: RotMatrix, sx: number, sy: number, sz: number, r: number, g: number, b: number, a: number)
	---@field setDebugBatchColor fun(self: SrcRenderer, r: number, g: number, b: number, a: number)
	---@field beginDebugBatch fun(self: SrcRenderer, primitive: integer)
	---@field addDebugBatchVertex fun(self: SrcRenderer, pos: Vector)
	---@field flushDebugBatch fun(self: SrcRenderer)
	---@field setDebugBatchTransform fun(self: SrcRenderer, pos: Vector, rot: RotMatrix)
	---@field resetDebugBatchTransform fun(self: SrcRenderer)
	---@field pushWorldTransform fun(self: SrcRenderer, pos: Vector, rot: RotMatrix)
	---@field popWorldTransform fun(self: SrcRenderer)
	---@field loadTexture fun(self: SrcRenderer, path: string): TextureDescriptor?
	---@field drawTexture fun(self: SrcRenderer, image: TextureDescriptor, x: number, y: number, width?: number, height?: number, r?: number, g?: number, b?: number, a?: number, flags?: integer): boolean
	---@field loadCMO fun(self: SrcRenderer, name: string): integer?
	---@field renderObject fun(self: SrcRenderer, modelId: integer, worldPos: Vector, worldRot: RotMatrix, texture?: TextureDescriptor)
	---@field menu SrcRendererMenu
	local SrcRenderer
end

do
	---@class SrcRendererMenu
	---@field button fun(label: string): boolean
	---@field textInput fun(label: string, value: string, maxLength: integer): string
	---@field focusNext fun()
	---@field checkbox fun(label: string, value: boolean): boolean, boolean
	---@field intSlider fun(label: string, value: integer, min: integer, max: integer, format?: string): boolean, integer
	---@field floatSlider fun(label: string, value: number, min: number, max: number, format?: string): boolean, number
	---@field comboBox fun(label: string, selectedIndex: integer, options: string[]): boolean, integer
	---@field nextMenuItemKey integer
	---@field nextMenuItemPosX number
	---@field nextMenuItemPosY number
	---@field nextMenuItemSizeX number
	---@field nextMenuItemSizeY number
	local SrcRendererMenu
end

do
	---@class SrcPhysics
	---@field lineIntersectLevel fun(posA: Vector, posB: Vector): Vector?, number?
	---@field lineIntersectHuman fun(posA: Vector, posB: Vector): Human?, number?
	---@field lineIntersectVehicle fun(posA: Vector, posB: Vector): Vehicle?, number?
	---@field lineIntersectLevelQuick fun(posA: Vector, posB: Vector): number?
	---@field lineIntersectHumanQuick fun(posA: Vector, posB: Vector): number?
	---@field lineIntersectVehicleQuick fun(posA: Vector, posB: Vector, includeWheels?: boolean): number?
	---@field lineIntersectAnyQuick fun(posA: Vector, posB: Vector, includeWheels?: boolean): Human|Vehicle|nil, number?
	local SrcPhysics
end

do
	---@class SrcMemory
	---@field getBaseAddress fun(): integer
	---@field getAddress fun(value: any): integer
	---@field toHexByte fun(value: integer): string
	---@field toHexShort fun(value: integer): string
	---@field toHexInt fun(value: integer): string
	---@field toHexLong fun(value: integer): string
	---@field toHexFloat fun(value: number): string
	---@field toHexDouble fun(value: number): string
	---@field toHexString fun(value: string): string
	---@field readByte fun(address: integer): integer
	---@field readUByte fun(address: integer): integer
	---@field readShort fun(address: integer): integer
	---@field readUShort fun(address: integer): integer
	---@field readInt fun(address: integer): integer
	---@field readUInt fun(address: integer): integer
	---@field readLong fun(address: integer): integer
	---@field readULong fun(address: integer): integer
	---@field readFloat fun(address: integer): number
	---@field readDouble fun(address: integer): number
	---@field readBytes fun(address: integer, count: integer): string
	---@field writeByte fun(address: integer, value: integer)
	---@field writeUByte fun(address: integer, value: integer)
	---@field writeShort fun(address: integer, value: integer)
	---@field writeUShort fun(address: integer, value: integer)
	---@field writeInt fun(address: integer, value: integer)
	---@field writeUInt fun(address: integer, value: integer)
	---@field writeLong fun(address: integer, value: integer)
	---@field writeULong fun(address: integer, value: integer)
	---@field writeFloat fun(address: integer, value: number)
	---@field writeDouble fun(address: integer, value: number)
	---@field writeBytes fun(address: integer, bytes: string)
	local SrcMemory
end

do
	---@class SrcPlayersApi
	---@field getCount fun(): integer
	---@field getAll fun(): Player[]
	---@field getByPhone fun(phone: integer|string): Player?
	---@field getNonBots fun(): Player[]
	---@field getBots fun(): Player[]
	local SrcPlayersApi
end

do
	---@class SrcHumansApi
	---@field getCount fun(): integer
	---@field getAll fun(): Human[]
	local SrcHumansApi
end

do
	---@class SrcItemsApi
	---@field getCount fun(): integer
	---@field getAll fun(): Item[]
	local SrcItemsApi
end

do
	---@class SrcItemTypesApi
	---@field getCount fun(): integer
	---@field getAll fun(): ItemType[]
	---@field getByName fun(name: string): ItemType?
	local SrcItemTypesApi
end

do
	---@class SrcVehiclesApi
	---@field getCount fun(): integer
	---@field getAll fun(): Vehicle[]
	---@field getNonTrafficCars fun(): Vehicle[]
	---@field getTrafficCars fun(): Vehicle[]
	local SrcVehiclesApi
end

do
	---@class SrcVehicleTypesApi
	---@field getCount fun(): integer
	---@field getAll fun(): VehicleType[]
	---@field getByName fun(name: string): VehicleType?
	local SrcVehicleTypesApi
end

do
	---@class SrcTrafficCarsApi
	---@field getCount fun(): integer
	---@field getAll fun(): TrafficCar[]
	local SrcTrafficCarsApi
end

do
	---@class SrcTexturesApi
	---@field getCount fun(): integer
	---@field getAll fun(): TextureDescriptor[]
	---@field getAllValid fun(): TextureDescriptor[]
	---@field getByGLTextureID fun(id: integer): TextureDescriptor?
	local SrcTexturesApi
end

do
	---@class SrcServerListEntriesApi
	---@field getCount fun(): integer
	---@field getPopulatedCount fun(): integer
	---@field getAll fun(): ServerListEntry[]
	local SrcServerListEntriesApi
end

do
	---@class Vector
	---@field x number
	---@field y number
	---@field z number
	---@field class string
	---@field __tostring fun(self: Vector): string
	---@field __add fun(self: Vector, other: Vector): Vector
	---@field __sub fun(self: Vector, other: Vector): Vector
	---@field __eq fun(self: Vector, other: Vector): boolean
	---@field __mul fun(self: Vector, other: number|RotMatrix): Vector
	---@field __div fun(self: Vector, scalar: number): Vector
	---@field __unm fun(self: Vector): Vector
	---@field add fun(self: Vector, other: Vector)
	---@field mult fun(self: Vector, scalar: number)
	---@field set fun(self: Vector, other: Vector)
	---@field cross fun(self: Vector, other: Vector)
	---@field clone fun(self: Vector): Vector
	---@field dist fun(self: Vector, other: Vector): number
	---@field distSquare fun(self: Vector, other: Vector): number
	---@field length fun(self: Vector): number
	---@field lengthSquare fun(self: Vector): number
	---@field dot fun(self: Vector, other: Vector): number
	---@field getBlockPos fun(self: Vector): integer, integer, integer
	---@field normalize fun(self: Vector)
	local Vector
end

do
	---@class RotMatrix
	---@field x1 number
	---@field y1 number
	---@field z1 number
	---@field x2 number
	---@field y2 number
	---@field z2 number
	---@field x3 number
	---@field y3 number
	---@field z3 number
	---@field class string
	---@field __tostring fun(self: RotMatrix): string
	---@field __mul fun(self: RotMatrix, other: RotMatrix): RotMatrix
	---@field set fun(self: RotMatrix, other: RotMatrix)
	---@field clone fun(self: RotMatrix): RotMatrix
	---@field getForward fun(self: RotMatrix): Vector
	---@field getUp fun(self: RotMatrix): Vector
	---@field getRight fun(self: RotMatrix): Vector
	---@field forwardUnit fun(self: RotMatrix): Vector
	---@field upUnit fun(self: RotMatrix): Vector
	---@field rightUnit fun(self: RotMatrix): Vector
	local RotMatrix
end

do
	---@class Player
	---@field class string
	---@field __tostring fun(self: Player): string
	---@field index integer
	---@field isActive boolean
	---@field data table
	---@field name string
	---@field isAdmin boolean
	---@field isSpeaking boolean
	---@field isBot boolean
	---@field isReady boolean
	---@field isGodMode boolean
	---@field isZombie boolean
	---@field human Human?
	---@field phoneNumber integer
	---@field subRosaID integer
	---@field money integer
	---@field teamMoney integer
	---@field budget integer
	---@field corporateRating integer
	---@field criminalRating integer
	---@field itemsBought integer
	---@field vehiclesBought integer
	---@field withdrawnBills integer
	---@field team integer
	---@field teamSwitchTimer integer
	---@field stocks integer
	---@field spawnTimer integer
	---@field gearX number
	---@field leftRightInput number
	---@field gearY number
	---@field forwardBackInput number
	---@field viewYawDelta number
	---@field viewPitch number
	---@field freeLookYaw number
	---@field freeLookPitch number
	---@field viewYaw number
	---@field viewPitchDelta number
	---@field inputFlags integer
	---@field lastInputFlags integer
	---@field realViewYaw number
	---@field realViewPitch number
	---@field controllerModeGear integer
	---@field zoomLevel number
	---@field inputType integer
	---@field menuTab integer
	---@field numActions integer
	---@field lastNumActions integer
	---@field numMenuButtons integer
	---@field gender integer
	---@field skinColor integer
	---@field hairColor integer
	---@field hair integer
	---@field eyeColor integer
	---@field model integer
	---@field suitColor integer
	---@field tieColor integer
	---@field head integer
	---@field necklace integer
	---@field botDestination Vector
	---@field getAction fun(self: Player, idx: integer): string?
	---@field getMenuButton fun(self: Player, idx: integer): string?
	local Player
end

do
	---@class Human
	---@field class string
	---@field __tostring fun(self: Human): string
	---@field index integer
	---@field isActive boolean
	---@field data table
	---@field stamina number
	---@field maxStamina number
	---@field vehicleSeat integer
	---@field despawnTime integer
	---@field spawnProtection integer
	---@field movementState integer
	---@field zoomLevel number
	---@field throwPitch number
	---@field damage integer
	---@field pos Vector
	---@field viewYaw number
	---@field viewPitch number
	---@field viewYaw2 number
	---@field strafeInput number
	---@field walkInput number
	---@field viewPitch2 number
	---@field inputFlags integer
	---@field lastInputFlags integer
	---@field numChatMessages integer
	---@field health number
	---@field bloodLevel number
	---@field chestHP number
	---@field headHP number
	---@field leftArmHP number
	---@field rightArmHP number
	---@field leftLegHP number
	---@field rightLegHP number
	---@field progressBar number
	---@field inventoryAnimationFlags integer
	---@field inventoryAnimationProgress integer
	---@field inventoryAnimationDuration integer
	---@field inventoryAnimationHand integer
	---@field inventoryAnimationSlot integer
	---@field inventoryAnimationCounterFinished integer
	---@field inventoryAnimationCounter integer
	---@field gender integer
	---@field head integer
	---@field skinColor integer
	---@field hairColor integer
	---@field hair integer
	---@field eyeColor integer
	---@field model integer
	---@field suitColor integer
	---@field tieColor integer
	---@field necklace integer
	---@field lastUpdatedWantedGroup integer
	---@field player Player?
	---@field vehicle Vehicle?
	---@field isAlive boolean
	---@field isImmortal boolean
	---@field isOnGround boolean
	---@field isStanding boolean
	---@field isBleeding boolean
	---@field getBone fun(self: Human, idx: integer): Bone?
	---@field getRigidBody fun(self: Human, idx: integer): RigidBody?
	---@field getInventorySlot fun(self: Human, idx: integer): InventorySlot?
	---@field teleport fun(self: Human, pos: Vector, rot?: RotMatrix)
	---@field setVelocity fun(self: Human, vel: Vector)
	---@field addVelocity fun(self: Human, vel: Vector)
	local Human
end

do
	---@class Item
	---@field class string
	---@field __tostring fun(self: Item): string
	---@field index integer
	---@field isActive boolean
	---@field data table
	---@field physicsSettledTimer integer
	---@field despawnTime integer
	---@field parentSlot integer
	---@field pos Vector
	---@field vel Vector
	---@field rot RotMatrix
	---@field bullets integer
	---@field numChildItems integer
	---@field cooldown integer
	---@field numChatMessages integer
	---@field cashSpread integer
	---@field cashAmount integer
	---@field cashPureValue integer
	---@field phoneNumber integer
	---@field callerRingTimer integer
	---@field displayPhoneNumber integer
	---@field enteredPhoneNumber integer
	---@field phoneTexture integer
	---@field phoneStatus integer
	---@field computerCurrentLine integer
	---@field computerTopLine integer
	---@field computerCursor integer
	---@field hasPhysics boolean
	---@field physicsSettled boolean
	---@field isStatic boolean
	---@field isInPocket boolean
	---@field type ItemType
	---@field rigidBody RigidBody
	---@field connectedPhone Item?
	---@field vehicle Vehicle?
	---@field grenadePrimer integer
	---@field parentHuman Human?
	---@field parentItem Item?
	---@field memoText string
	---@field getChildItem fun(self: Item, idx: integer): Item?
	---@field computerSetLine fun(self: Item, line: integer, text: string)
	---@field computerSetLineColors fun(self: Item, line: integer, fg: integer, bg: integer)
	---@field computerSetColor fun(self: Item, fg: integer, bg: integer)
	local Item
end

do
	---@class ItemType
	---@field class string
	---@field __tostring fun(self: ItemType): string
	---@field index integer
	---@field name string
	---@field price integer
	---@field mass number
	---@field fireRate integer
	---@field magazineAmmo integer
	---@field bulletType integer
	---@field bulletVelocity number
	---@field bulletSpread number
	---@field numHands integer
	---@field rightHandPos Vector
	---@field leftHandPos Vector
	---@field primaryGripStiffness number
	---@field primaryGripRotation RotMatrix
	---@field secondaryGripStiffness number
	---@field secondaryGripRotation RotMatrix
	---@field boundsCenter Vector
	---@field gunHoldingPos Vector
	---@field isGun boolean
	---@field getCanMountTo fun(self: ItemType, idx: integer): boolean
	---@field setCanMountTo fun(self: ItemType, idx: integer, enabled: boolean)
	local ItemType
end

do
	---@class Vehicle
	---@field class string
	---@field __tostring fun(self: Vehicle): string
	---@field index integer
	---@field isActive boolean
	---@field controllableState integer
	---@field health number
	---@field color integer
	---@field despawnTime integer
	---@field pos Vector
	---@field pos2 Vector
	---@field rot RotMatrix
	---@field vel Vector
	---@field gearX number
	---@field steerControl number
	---@field gearY number
	---@field gasControl number
	---@field engineRPM number
	---@field bladeBodyID integer
	---@field numSeats integer
	---@field numWheels integer
	---@field type VehicleType
	---@field isLocked boolean
	---@field data table
	---@field lastDriver Player?
	---@field rigidBody RigidBody
	---@field trafficCar TrafficCar?
	---@field getIsWindowBroken fun(self: Vehicle, idx: integer): boolean
	---@field setIsWindowBroken fun(self: Vehicle, idx: integer, broken: boolean)
	---@field getWheel fun(self: Vehicle, idx: integer): Wheel?
	local Vehicle
end

do
	---@class VehicleType
	---@field class string
	---@field __tostring fun(self: VehicleType): string
	---@field index integer
	---@field name string
	---@field controllableState integer
	---@field price integer
	---@field mass number
	---@field acceleration number
	---@field numWheels integer
	---@field numSeats integer
	---@field usesExternalModel boolean
	local VehicleType
end

do
	---@class TrafficCar
	---@field class string
	---@field __tostring fun(self: TrafficCar): string
	---@field index integer
	---@field pos Vector
	---@field vel Vector
	---@field yaw number
	---@field rot RotMatrix
	---@field color integer
	---@field state integer
	---@field type VehicleType
	---@field human Human?
	---@field isBot boolean
	---@field isAggressive boolean
	---@field vehicle Vehicle?
	local TrafficCar
end

do
	---@class Wheel
	---@field class string
	---@field spin number
	---@field visualHeight number
	---@field vehicleHeight number
	---@field skid number
	---@field rigidBody RigidBody
	local Wheel
end

do
	---@class TextureDescriptor
	---@field class string
	---@field __tostring fun(self: TextureDescriptor): string
	---@field index integer
	---@field width integer
	---@field height integer
	---@field mipLevels integer
	---@field internalFormat integer
	---@field pixelFormat integer
	---@field wrapS integer
	---@field wrapT integer
	---@field minFilter integer
	---@field magFilter integer
	---@field unknown24 integer
	---@field flags integer
	---@field glTextureID integer
	---@field isValid boolean
	local TextureDescriptor
end

do
	---@class ServerListEntry
	---@field class string
	---@field __tostring fun(self: ServerListEntry): string
	---@field index integer
	---@field versionMajor integer
	---@field versionMinor integer
	---@field networkVersion integer
	---@field name string
	---@field srkIdentifier string
	---@field port integer
	---@field ping integer
	---@field gameType integer
	---@field isPassworded boolean
	---@field playerCount integer
	---@field maxPlayerCount integer
	---@field ip string
	local ServerListEntry
end

do
	---@class InventorySlot
	---@field count integer
	---@field class string
	---@field primaryItem Item?
	---@field secondaryItem Item?
	local InventorySlot
end

do
	---@class Bone
	---@field class string
	---@field rigidBody RigidBody?
	---@field pos Vector
	---@field pos2 Vector
	---@field vel Vector
	---@field rot RotMatrix
	---@field mass number
	---@field scale Vector
	---@field scaleReciprocal Vector
	---@field smallestScaleFactor number
	local Bone
end

do
	---@class RigidBody
	---@field type integer
	---@field linkedHumanOrItemID integer
	---@field localIndex integer
	---@field index integer
	---@field pos Vector
	---@field vel Vector
	---@field rot RotMatrix
	---@field rotVel Vector
	---@field mass number
	---@field scale Vector
	---@field scaleReciprocal Vector
	---@field smallestScaleFactor number
	---@field unused number
	---@field vehicleDebugBoxSize Vector
	---@field suspensionRelated number
	---@field class string
	---@field __tostring fun(self: RigidBody): string
	---@field isActive boolean
	---@field data table
	---@field isSettled boolean
	---@field bondTo fun(self: RigidBody, other: RigidBody, thisLocalPos: Vector, otherLocalPos: Vector): any
	---@field bondRotTo fun(self: RigidBody, other: RigidBody): any
	---@field bondToLevel fun(self: RigidBody, localPos: Vector, globalPos: Vector): any
	---@field collideLevel fun(self: RigidBody, localPos: Vector, normal: Vector, a: number, b: number, c: number, d: number)
	local RigidBody
end
