--# selene: allow(unused_variable)
--# selene: allow(unscoped_variables)
---@meta

do
	---@class SrcCamera
	---@field pos Vector
	---@field rot RotMatrix
	---@field fov number
	local SrcCamera
end

do
	---@class SrcHudWidgets
	---@field minimap table
	---@field crosshair table
	---@field staminaBar table
	---@field progressBar table
	---@field chatFeed table
	---@field moneyText table
	---@field teamMoneyText table
	---@field mapToggleHint table
	local SrcHudWidgets
end

do
	---@class SrcLocalClient
	---@field player Player?
	---@field human Human?
	---@field spectatingHuman Human?
	---@field camera SrcCamera
	---@field isMapToggled integer
	---@field isInGame integer
	---@field menuState integer
	---@field isPauseMenu integer
	---@field ping integer
	---@field isMapAutoGenerated integer
	---@field mapLegendPosX number
	---@field mapLegendPosY number
	---@field serverAddress string
	---@field serverPort integer
	---@field ticksSinceReset integer
	---@field hud SrcHudWidgets
	local SrcLocalClient
end

do
	---@class SrcSounds
	---@field loadSound fun(self: SrcSounds, path: string, maxDistance?: number): integer
	---@field playSound3D fun(self: SrcSounds, soundId: integer, position: Vector, volume?: number, pitch?: number): boolean
	local SrcSounds
end

do
	---@class SrcPngImage
	---@field atlas integer
	---@field id integer
	---@field width integer
	---@field height integer
	---@field path string
	---@field isValid boolean
	local SrcPngImage
end

do
	---@class SrcRenderer
	---@field enableHead boolean
	---@field drawText fun(self: SrcRenderer, text: string, x: number, y: number, size: number, r: number, g: number, b: number, a: number, align: integer)
	---@field worldToScreenPosition fun(self: SrcRenderer, world: Vector): number?, number?
	---@field drawSquare2D fun(self: SrcRenderer, x: number, y: number, size: number, r: number, g: number, b: number, a: number)
	---@field drawRectangle2D fun(self: SrcRenderer, x: number, y: number, w: number, h: number, r: number, g: number, b: number, a: number)
	---@field drawRectangleRotated2D fun(self: SrcRenderer, x: number, y: number, w: number, h: number, rot: number, r: number, g: number, b: number, a: number)
	---@field drawMapCircle fun(self: SrcRenderer, x: number, y: number, radius: number, r: number, g: number, b: number, a: number)
	---@field drawDebugLine3D fun(self: SrcRenderer, from: Vector, to: Vector, r: number, g: number, b: number, a: number)
	---@field drawDebugWireBox3D fun(self: SrcRenderer, pos: Vector, rot: RotMatrix, sx: number, sy: number, sz: number, r: number, g: number, b: number, a: number)
	---@field drawDebugSolidBox3D fun(self: SrcRenderer, pos: Vector, rot: RotMatrix, sx: number, sy: number, sz: number, r: number, g: number, b: number, a: number)
	---@field setDebugBatchColor fun(self: SrcRenderer, r: number, g: number, b: number, a: number)
	---@field beginDebugBatch fun(self: SrcRenderer, primitive: integer)
	---@field addDebugBatchVertex fun(self: SrcRenderer, pos: Vector)
	---@field flushDebugBatch fun(self: SrcRenderer)
	---@field setDebugBatchTransform fun(self: SrcRenderer, pos: Vector, rot: RotMatrix)
	---@field resetDebugBatchTransform fun(self: SrcRenderer)
	---@field loadPng fun(self: SrcRenderer, path: string): SrcPngImage?
	---@field drawTexture fun(self: SrcRenderer, image: SrcPngImage, x: number, y: number, width?: number, height?: number, r?: number, g?: number, b?: number, a?: number, flags?: integer): boolean
	---@field loadCMO fun(self: SrcRenderer, name: string): integer?
	---@field renderObject fun(self: SrcRenderer, modelId: integer, worldPos: Vector, worldRot: RotMatrix, colorPrimary?: integer, colorSecondary?: integer, flags?: integer)
	local SrcRenderer
end

do
	---@class SrcPhysics
	---@field lineIntersectLevel fun(posA: Vector, posB: Vector): Vector?, number?
	---@field lineIntersectHuman fun(posA: Vector, posB: Vector): Human?, number?
	---@field lineIntersectVehicle fun(posA: Vector, posB: Vector): Vehicle?, number?
	---@field lineIntersectLevelQuick fun(posA: Vector, posB: Vector): number?
	---@field lineIntersectHumanQuick fun(posA: Vector, posB: Vector): number?
	---@field lineIntersectVehicleQuick fun(posA: Vector, posB: Vector, includeWheels?: boolean): number?
	---@field lineIntersectAnyQuick fun(posA: Vector, posB: Vector, includeWheels?: boolean): Human|Vehicle|nil, number?
	local SrcPhysics
end

do
	---@class SrcMemory
	---@field getBaseAddress fun(): integer
	---@field getAddress fun(value: any): integer
	---@field readByte fun(address: integer): integer
	---@field readUByte fun(address: integer): integer
	---@field readShort fun(address: integer): integer
	---@field readUShort fun(address: integer): integer
	---@field readInt fun(address: integer): integer
	---@field readUInt fun(address: integer): integer
	---@field readLong fun(address: integer): integer
	---@field readULong fun(address: integer): integer
	---@field readFloat fun(address: integer): number
	---@field readDouble fun(address: integer): number
	---@field readBytes fun(address: integer, count: integer): string
	---@field writeByte fun(address: integer, value: integer)
	---@field writeUByte fun(address: integer, value: integer)
	---@field writeShort fun(address: integer, value: integer)
	---@field writeUShort fun(address: integer, value: integer)
	---@field writeInt fun(address: integer, value: integer)
	---@field writeUInt fun(address: integer, value: integer)
	---@field writeLong fun(address: integer, value: integer)
	---@field writeULong fun(address: integer, value: integer)
	---@field writeFloat fun(address: integer, value: number)
	---@field writeDouble fun(address: integer, value: number)
	---@field writeBytes fun(address: integer, bytes: string)
	local SrcMemory
end

do
	---@class SrcPlayersApi
	---@field getCount fun(): integer
	---@field getAll fun(): Player[]
	---@field getByPhone fun(phone: integer|string): Player?
	---@field getNonBots fun(): Player[]
	---@field getBots fun(): Player[]
	local SrcPlayersApi
end

do
	---@class SrcHumansApi
	---@field getCount fun(): integer
	---@field getAll fun(): Human[]
	local SrcHumansApi
end

do
	---@class SrcItemsApi
	---@field getCount fun(): integer
	---@field getAll fun(): Item[]
	local SrcItemsApi
end

do
	---@class SrcItemTypesApi
	---@field getCount fun(): integer
	---@field getAll fun(): ItemType[]
	---@field getByName fun(name: string): ItemType?
	local SrcItemTypesApi
end

do
	---@class SrcVehiclesApi
	---@field getCount fun(): integer
	---@field getAll fun(): Vehicle[]
	---@field getNonTrafficCars fun(): Vehicle[]
	---@field getTrafficCars fun(): Vehicle[]
	local SrcVehiclesApi
end

do
	---@class SrcVehicleTypesApi
	---@field getCount fun(): integer
	---@field getAll fun(): VehicleType[]
	---@field getByName fun(name: string): VehicleType?
	local SrcVehicleTypesApi
end

do
	---@class SrcTrafficCarsApi
	---@field getCount fun(): integer
	---@field getAll fun(): TrafficCar[]
	local SrcTrafficCarsApi
end

do
	---@class SrcTexturesApi
	---@field getCount fun(): integer
	---@field getAll fun(): TextureDescriptor[]
	---@field getAllValid fun(): TextureDescriptor[]
	---@field getByGLTextureID fun(id: integer): TextureDescriptor?
	local SrcTexturesApi
end

do
	---@class SrcServerListEntriesApi
	---@field getCount fun(): integer
	---@field getPopulatedCount fun(): integer
	---@field getAll fun(): ServerListEntry[]
	local SrcServerListEntriesApi
end

do
	---@class Vector
	---@field x number
	---@field y number
	---@field z number
	---@field add fun(self: Vector, other: Vector)
	---@field mult fun(self: Vector, scalar: number)
	---@field set fun(self: Vector, other: Vector)
	---@field cross fun(self: Vector, other: Vector)
	---@field clone fun(self: Vector): Vector
	---@field dist fun(self: Vector, other: Vector): number
	---@field distSquare fun(self: Vector, other: Vector): number
	---@field length fun(self: Vector): number
	---@field lengthSquare fun(self: Vector): number
	---@field dot fun(self: Vector, other: Vector): number
	---@field getBlockPos fun(self: Vector): integer, integer, integer
	---@field normalize fun(self: Vector)
	local Vector
end

do
	---@class RotMatrix
	---@field x1 number
	---@field y1 number
	---@field z1 number
	---@field x2 number
	---@field y2 number
	---@field z2 number
	---@field x3 number
	---@field y3 number
	---@field z3 number
	---@field set fun(self: RotMatrix, other: RotMatrix)
	---@field clone fun(self: RotMatrix): RotMatrix
	---@field getForward fun(self: RotMatrix): Vector
	---@field getUp fun(self: RotMatrix): Vector
	---@field getRight fun(self: RotMatrix): Vector
	---@field forwardUnit fun(self: RotMatrix): Vector
	---@field upUnit fun(self: RotMatrix): Vector
	---@field rightUnit fun(self: RotMatrix): Vector
	local RotMatrix
end

do
	---@class Player
	---@field index integer
	---@field name string
	---@field isBot boolean
	---@field isReady boolean
	---@field human Human?
	---@field phoneNumber integer
	---@field subRosaID integer
	---@field getAction fun(self: Player, idx: integer): string?
	---@field getMenuButton fun(self: Player, idx: integer): string?
	local Player
end

do
	---@class Human
	---@field index integer
	---@field pos Vector
	---@field player Player?
	---@field vehicle Vehicle?
	---@field isAlive boolean
	---@field getBone fun(self: Human, idx: integer): Bone?
	---@field getRigidBody fun(self: Human, idx: integer): RigidBody?
	---@field teleport fun(self: Human, pos: Vector, rot?: RotMatrix)
	---@field setVelocity fun(self: Human, vel: Vector)
	---@field addVelocity fun(self: Human, vel: Vector)
	local Human
end

do
	---@class Item
	---@field index integer
	---@field pos Vector
	---@field vel Vector
	---@field rot RotMatrix
	---@field type ItemType
	---@field rigidBody RigidBody
	---@field parentHuman Human?
	---@field parentItem Item?
	---@field getChildItem fun(self: Item, idx: integer): Item?
	local Item
end

do
	---@class ItemType
	---@field index integer
	---@field name string
	---@field isGun boolean
	---@field getCanMountTo fun(self: ItemType, idx: integer): boolean
	---@field setCanMountTo fun(self: ItemType, idx: integer, enabled: boolean)
	local ItemType
end

do
	---@class Vehicle
	---@field index integer
	---@field type VehicleType
	---@field rigidBody RigidBody
	---@field trafficCar TrafficCar?
	---@field getIsWindowBroken fun(self: Vehicle, idx: integer): boolean
	---@field setIsWindowBroken fun(self: Vehicle, idx: integer, broken: boolean)
	---@field getWheel fun(self: Vehicle, idx: integer): Wheel?
	local Vehicle
end

do
	---@class VehicleType
	---@field index integer
	---@field name string
	---@field usesExternalModel boolean
	local VehicleType
end

do
	---@class TrafficCar
	---@field index integer
	---@field pos Vector
	---@field vel Vector
	---@field rot RotMatrix
	---@field vehicle Vehicle?
	local TrafficCar
end

do
	---@class Wheel
	---@field spin number
	---@field skid number
	---@field rigidBody RigidBody
	local Wheel
end

do
	---@class TextureDescriptor
	---@field index integer
	---@field width integer
	---@field height integer
	---@field glTextureID integer
	---@field isValid boolean
	local TextureDescriptor
end

do
	---@class ServerListEntry
	---@field index integer
	---@field name string
	---@field port integer
	---@field ping integer
	---@field playerCount integer
	---@field maxPlayerCount integer
	---@field ip string
	local ServerListEntry
end

do
	---@class Bone
	---@field pos Vector
	---@field pos2 Vector
	---@field vel Vector
	---@field rot RotMatrix
	local Bone
end

do
	---@class RigidBody
	---@field index integer
	---@field pos Vector
	---@field vel Vector
	---@field rot RotMatrix
	---@field rotVel Vector
	---@field mass number
	---@field isActive boolean
	---@field isSettled boolean
	---@field bondTo fun(self: RigidBody, other: RigidBody, thisLocalPos: Vector, otherLocalPos: Vector): any
	---@field bondRotTo fun(self: RigidBody, other: RigidBody): any
	---@field bondToLevel fun(self: RigidBody, localPos: Vector, globalPos: Vector): any
	---@field collideLevel fun(self: RigidBody, localPos: Vector, normal: Vector, a: number, b: number, c: number, d: number)
	local RigidBody
end
